name: Build, Test & Deploy
on: push

jobs:
  build_test_deploy:
    name: 'FunctionApp Build, Test & Deploy'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      
    - name: Get WebApp publish profile
      id: webapp
      uses: ./
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      with:
        resourceGroupName: ${{ secrets.RESOURCE_GROUP_NAME_DEV }}
        appName: ${{ secrets.RESOURCE_FUNCTIONAPP_NAME_DEV }}
        slot-name: testing
       
    - name: Show WebApp Profile
      shell: bash
      run: |
        echo "WebApp: ${{ steps.webapp.outputs.profile }}"
