name: Build and deploy ASP.Net Core app to Azure Web App - x00180702bpApp

env:
  AZURE_WEBAPP_NAME: BloodPressureCalculator            # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'publish'              # set this to the path to your web app project

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          
      - name: Build for Release
        run: dotnet build --configuration Release
      - name: Run unit tests
        run: dotnet test bpUnitTestProject/bpUnitTestProject.csproj --no-restore --collect "Code coverage" -l:trx

      - name: Install dependencies
        run: dotnet restore
        
      - name: Publish Unit Test Results
        uses: dorny/test-reporter@v1
        with:
          artifact: ''
          name: MS Tests                  
          path: '**.trx'
          reporter: 'dotnet-trx'   

      - name: Run unit tests
        run: dotnet test bpUnitTestProject/bpUnitTestProject.csproj --no-restore --collect "Code coverage" -l:trx

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}                        # your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/BloodPressureCalculator'
